<?php
/**
 * Database Configuration - auto-generated by docker-entrypoint.sh
 * Do not edit this file directly when running in Docker.
 * Set DB_* environment variables in docker-compose.yml instead.
 */

define('DB_HOST', 'db');
define('DB_PORT', '3306');
define('DB_USER', 'gapi_user');
define('DB_PASSWORD', 'gapi_password');
define('DB_NAME', 'gapi');

function getDb(): PDO {
    static $pdo = null;
    if ($pdo === null) {
        $dsn = 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4';
        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ];
        try {
            $pdo = new PDO($dsn, DB_USER, DB_PASSWORD, $options);
        } catch (PDOException $e) {
            apiLog('Database connection failed.', $e);
            apiErrorResponse('Database connection failed. Please check the staging database configuration.', 500, $e);
        }
    }
    return $pdo;
}

function generateUuid(): string {
    $data = random_bytes(16);
    $data[6] = chr(ord($data[6]) & 0x0f | 0x40);
    $data[8] = chr(ord($data[8]) & 0x3f | 0x80);
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}

function jsonResponse($data, int $status = 200): void {
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($data);
    exit;
}

function getJsonBody(): array {
    $raw = file_get_contents('php://input');
    if (empty($raw)) return [];
    $decoded = json_decode($raw, true);
    return is_array($decoded) ? $decoded : [];
}

function checkRateLimit(string $action, int $maxRequests, int $windowSecs): void {
    $db = getDb();
    $ip = $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0';
    $windowStart = date('Y-m-d H:i:s', time() - $windowSecs);
    $db->prepare('DELETE FROM gapi_rate_limits WHERE created_at < ?')->execute([$windowStart]);
    $stmt = $db->prepare('SELECT COUNT(*) as cnt FROM gapi_rate_limits WHERE ip_address = ? AND action = ? AND created_at >= ?');
    $stmt->execute([$ip, $action, $windowStart]);
    $row = $stmt->fetch();
    if ((int)$row['cnt'] >= $maxRequests) {
        jsonResponse(['message' => 'Too many requests from this IP, please try again later.'], 429);
    }
    $db->prepare('INSERT INTO gapi_rate_limits (ip_address, action) VALUES (?, ?)')->execute([$ip, $action]);
}
